import assert from 'node:assert/strict';
import fs from 'node:fs';
const db=fs.readFileSync('modules/db.js','utf8');
const app=fs.readFileSync('app.js','utf8');
const nav=fs.readFileSync('modules/navigation.js','utf8');
assert.match(db,/normalizeIntroCanvasItem/);
assert.match(db,/\['text', 'image', 'video'\]/);
assert.match(db,/localOnly: !syncResult\?\.ok/);
assert.match(app,/pullSubjectDetailsFromServer/);
assert.match(app,/mergeSubjectDetailsFromServer\(remoteSubjectDetails\)/);
assert.match(app,/Chưa thể đăng công khai vì đồng bộ dữ liệu thất bại/);
assert.match(app,/window\._adminSubjectPreview/);
assert.match(app,/adminIntroCanvasPointerDown/);
assert.match(app,/adminIntroCanvasAlign/);
assert.match(nav,/renderIntroCanvas/);
assert.match(nav,/safeIntroUrl/);
assert.match(nav,/canDisplayPublishedCanvas/);
assert.match(nav,/student-intro-canvas-image-error/);
assert.match(nav,/student-intro-canvas--text-only/);
assert.match(nav,/student-intro-canvas--media-only/);
assert.match(nav,/student-intro-canvas--mixed/);
assert.match(nav,/student-intro-canvas-backdrop/);
assert.match(nav,/student-intro-canvas-course-label/);
console.log('subject canvas checks passed');
assert.match(db, /x: clamp\(item\.x, 8, 0, 92\)/);
assert.match(db, /y: clamp\(item\.y, 8 \+ index \* 12, 0, 92\)/);
assert.match(db, /width: clamp\(item\.width, type === 'text' \? 42 : 36, 12, 100\)/);
assert.match(db, /height: clamp\(item\.height, type === 'text' \? 18 : 28, 8, 100\)/);
