const assert = require('node:assert/strict');
const fs = require('node:fs');
const app = fs.readFileSync('app.js', 'utf8');
const nav = fs.readFileSync('modules/navigation.js', 'utf8');
assert.match(app, /selector:\s*'#admin-review-lesson-document-editor'/);
for (const token of ['undo redo', 'blocks', 'underline', 'forecolor backcolor', 'link image media table', 'wordcount']) assert.match(app, new RegExp(token));
for (const name of ['_reviewLessonSubjectId', '_reviewLessonChapterId', '_reviewLessonId', '_reviewLessonDocumentEditor', '_reviewLessonMediaItems', '_reviewLessonSelectedMediaId']) assert.match(app, new RegExp(name));
for (const name of ['addReviewLessonMedia', 'renderReviewLessonMediaCanvas', 'selectReviewLessonMedia', 'updateReviewLessonMedia', 'startReviewLessonMediaDrag', 'moveReviewLessonMediaDrag', 'endReviewLessonMediaDrag', 'deleteReviewLessonMedia', 'saveReviewLesson']) assert.match(app, new RegExp(String.raw`function ${name}\(`));
assert.match(nav, /function sanitizeReviewLessonHtml\(/);
assert.match(nav, /block\.type === 'lessonDocument'/);
assert.match(nav, /<article class="review-lesson-document">\$\{sanitizeReviewLessonHtml\(block\.content\)\}<\/article>/);
console.log('review lesson editor checks passed');
assert.match(app, /plugins:'lists link image media table wordcount'/);
assert.match(app, /function _reviewLegacyMediaHtml\(/);
assert.match(app, /a\.lesson\.blocks=\[doc\]/);
assert.match(nav, /'img','video','source','iframe'/);
assert.match(nav, /tag === 'img' && width/);
console.log('inline review media checks passed');
assert.match(app, /reviewFloatingMedia/);
assert.match(app, /function reviewLessonToggleFloatingMedia\(/);
assert.match(app, /data-review-float-x/);
assert.match(nav, /review-floating-media/);
console.log('floating media checks passed');
assert.match(app, /body\.appendChild\(image\); parent\.remove\(\)/);
console.log('floating media detachment checks passed');
assert.match(app, /async function saveReviewLesson\(status\)/);
assert.match(app, /DB\.saveSubjectDetails\(_reviewLessonSubjectId,a\.details,!publishing,idToken\)/);
assert.match(app, /a\.details\.status='published'/);
assert.match(app, /image\.setAttribute\('contenteditable', 'false'\)/);
assert.match(app, /editor\.focus\(\)/);
console.log('review save and keyboard focus checks passed');
const db = fs.readFileSync('modules/db.js', 'utf8');
assert.match(db, /'lessonDocument'/);
assert.match(db, /\['heading', 'text', 'lessonDocument'/);
console.log('lesson document normalization checks passed');
